version: '3'
services:
  web:
    image: nginx:latest
    ports:
       - "8084:80"
    volumes:
       - ./home/udev-2/Project:/usr/share/nginx/html:ro
       - ./default.conf:/etc/nginx/conf.d/default.conf:ro
